/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas;

import config.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario19
 */
public class Formulario extends javax.swing.JFrame {
    Conexion cn = new Conexion();
    Connection con;
    ResultSet rs ;
    Statement st;
    DefaultTableModel model;
    int id;
    
    public Formulario() {
        initComponents();
        setLocationRelativeTo(null);
        listas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEspecialidad = new javax.swing.JComboBox<>();
        txtMante = new javax.swing.JRadioButton();
        txtCantidad = new javax.swing.JSpinner();
        txtId = new javax.swing.JTextField();
        txtMarca = new javax.swing.JTextField();
        txtModelo = new javax.swing.JTextField();
        txtFabricacion = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListaDatos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnAgregar_RonaldinhoCcencho = new javax.swing.JButton();
        btnEliminar_RonaldinhoCcencho = new javax.swing.JButton();
        btnModificar_RonaldinhoCcencho = new javax.swing.JButton();
        btnLimpiar_RonaldinhoCcencho = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CRUD AS231");

        jLabel2.setText("Nº Serie");

        jLabel3.setText("Marca");

        jLabel4.setText("Modelo");

        jLabel5.setText("E.Especialidad");

        jLabel6.setText("Mantenimiento");

        jLabel7.setText("Cantidad:");

        txtEspecialidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "selecione", "Analisis de Sistemas", "Produccion Agraria", " " }));

        txtMante.setText("6 meses");

        txtId.setEditable(false);
        txtId.setEnabled(false);

        jLabel8.setText("Fabricaciòn:");

        ListaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nº Serie", "Marca", "Modelo", "Especialidad", "Mantenimiento", "Cantidad", "Fabricaciòn", "EstadoE"
            }
        ));
        ListaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ListaDatos);
        if (ListaDatos.getColumnModel().getColumnCount() > 0) {
            ListaDatos.getColumnModel().getColumn(0).setMinWidth(50);
            ListaDatos.getColumnModel().getColumn(0).setPreferredWidth(50);
            ListaDatos.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        jLabel9.setText("Estado E");

        btnAgregar_RonaldinhoCcencho.setText("Agregar");
        btnAgregar_RonaldinhoCcencho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar_RonaldinhoCcenchoActionPerformed(evt);
            }
        });

        btnEliminar_RonaldinhoCcencho.setText("Eliminar");
        btnEliminar_RonaldinhoCcencho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminar_RonaldinhoCcenchoActionPerformed(evt);
            }
        });

        btnModificar_RonaldinhoCcencho.setText("Modificar");
        btnModificar_RonaldinhoCcencho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar_RonaldinhoCcenchoActionPerformed(evt);
            }
        });

        btnLimpiar_RonaldinhoCcencho.setText("Nuevo");
        btnLimpiar_RonaldinhoCcencho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar_RonaldinhoCcenchoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(312, 312, 312)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addComponent(jLabel7)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar_RonaldinhoCcencho)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMante)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                                .addComponent(txtFabricacion))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtMarca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addComponent(txtModelo, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnEliminar_RonaldinhoCcencho)
                        .addGap(26, 26, 26)
                        .addComponent(btnModificar_RonaldinhoCcencho)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpiar_RonaldinhoCcencho)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3))
                            .addComponent(txtMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtMante))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFabricacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar_RonaldinhoCcencho)
                            .addComponent(btnEliminar_RonaldinhoCcencho)
                            .addComponent(btnModificar_RonaldinhoCcencho)
                            .addComponent(btnLimpiar_RonaldinhoCcencho)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregar_RonaldinhoCcenchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar_RonaldinhoCcenchoActionPerformed
       agregar();
       listas();
       nuevo();
    }//GEN-LAST:event_btnAgregar_RonaldinhoCcenchoActionPerformed

    private void ListaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaDatosMouseClicked
      int row = ListaDatos.getSelectedRow();
      if(row ==-1){
      JOptionPane.showMessageDialog(null, "No se selecciono datos");
      }else{
      id = Integer.parseInt((String)ListaDatos.getValueAt(row, 0).toString());
      String marca = (String)ListaDatos.getValueAt(row, 1);
      String modelo = (String)ListaDatos.getValueAt(row, 2);
      String espe = (String)ListaDatos.getValueAt(row, 3).toString();
      String mante = (String)ListaDatos.getValueAt(row, 4);
      int cantidad = Integer.parseInt((String)ListaDatos.getValueAt(row, 5).toString());
      String fabri = (String)ListaDatos.getValueAt(row, 6);
      String estado = (String)ListaDatos.getValueAt(row, 7);
      
      txtId.setText(""+id);
      txtMarca.setText(marca);
      txtModelo.setText(modelo);
      txtMante.setText(mante);
      txtFabricacion.setText(fabri);
      txtEstado.setText(estado);
      txtEspecialidad.setSelectedItem(espe);
      txtCantidad.setValue(cantidad);
      }
    }//GEN-LAST:event_ListaDatosMouseClicked

    private void btnModificar_RonaldinhoCcenchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar_RonaldinhoCcenchoActionPerformed
        modificar();
        listas();
        nuevo();
    }//GEN-LAST:event_btnModificar_RonaldinhoCcenchoActionPerformed

    private void btnEliminar_RonaldinhoCcenchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminar_RonaldinhoCcenchoActionPerformed
        eliminar();
        listas();
        nuevo();
    }//GEN-LAST:event_btnEliminar_RonaldinhoCcenchoActionPerformed

    private void btnLimpiar_RonaldinhoCcenchoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar_RonaldinhoCcenchoActionPerformed
        nuevo();
    }//GEN-LAST:event_btnLimpiar_RonaldinhoCcenchoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }
    void listas(){
        String sql = "Select * from producto";
        try {
            con = cn.getConnection();
            st = con.createStatement();
            rs = st.executeQuery(sql);
            Object[] producto = new Object[8];
            model= (DefaultTableModel)ListaDatos.getModel();
            while(rs.next()){
             producto[0] = rs.getInt("id");
             producto[1] = rs.getString("marca");
             producto[2] = rs.getString("modelo");
             producto[3] = rs.getString("especialidad");
             producto[4] = rs.getString("mantenimiento");
             producto[5] = rs.getInt("cantidad");
             producto[6] = rs.getString("fabricacion");
             producto[7] = rs.getString("estado");
             model.addRow(producto);
            }
            ListaDatos.getModel();
        } catch (Exception e) {
            System.out.println("ERROR"+e);
        }
    }
    
    void agregar(){
    String marca = txtMarca.getText();
    String modelo = txtModelo.getText();
    String especialidad = txtEspecialidad.getItemAt(1);
    String mantenimiento = txtMante.getText();
    int cantidad = txtCantidad.getComponentCount();
    String fabricacion = txtFabricacion.getText();
    String estado = txtEstado.getText();
    
    String sql = "Insert into producto (marca,modelo,especialidad,mantenimiento,cantidad,fabricacion,estado)values('"+marca+"','"+ modelo +"','"+especialidad+"'," + "'"+mantenimiento+"','"+ cantidad +"','"+fabricacion+"','"+estado+"')";
        try {
            if(modelo.equals("") || marca.equals("") || especialidad.equals("")|| mantenimiento.equals("") || fabricacion.equals("") || estado.equals("") ){
                JOptionPane.showMessageDialog(null, "Ingrese datos");
            }else{
                try {
                    con = cn.getConnection();
                    st = con.createStatement();
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Datos Ingresados");
                    limpiarTable(model);
                } catch (Exception e) {
                    System.out.println("ERROR");
                }
            }
        } catch (Exception e) {
        }
    }
    
    void modificar(){
    String marca = txtMarca.getText();
    String modelo = txtModelo.getText();
    String espe = txtEspecialidad.getSelectedItem().toString();
    String mante = txtMante.getText();
    String cantidad = txtCantidad.getValue().toString();
    String fabricacion = txtFabricacion.getText();
    String estado = txtEstado.getText();
    
    String sql = "Update producto set marca='"+ marca +"',modelo='"+ modelo +"',especialidad='"+ espe +"',mantenimiento='"+mante+"',cantidad='"+cantidad+"',fabricacion='"+fabricacion+"',estado='"+estado+"' where id="+id;
       try {
            if(modelo.equals("") || marca.equals("")|| mante.equals("") || fabricacion.equals("") || estado.equals("") ){
                JOptionPane.showMessageDialog(null, "no encontro datos");
                limpiarTable(model);
            }else{
                try {
                    con = cn.getConnection();
                    st = con.createStatement();
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Datos  Modificados");
                    limpiarTable(model);
                } catch (Exception e) {
                    System.out.println("ERROR");
                }
            }
        } catch (Exception e) {
        }
    }
    
    void eliminar(){
    String marca = txtMarca.getText();
    String modelo = txtModelo.getText();
    String espe = txtEspecialidad.getItemAt(1);
    String mante = txtMante.getText();
    int cantidad = txtCantidad.getComponentCount();
    String fabricacion = txtFabricacion.getText();
    String estado = txtEstado.getText();
    String sql = "Delete from producto where id="+id;
    
        try {
             if(modelo.equals("") || marca.equals("") || espe.equals("")|| mante.equals("") || fabricacion.equals("") || estado.equals("") ){
                JOptionPane.showMessageDialog(null, "no encontro datos");
                limpiarTable(model);
             }else{
            con = cn.getConnection();
            st = con.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Datos eliminados");
            limpiarTable(model);
             }  } catch (Exception e) {
        }
    };
    void nuevo(){
    txtId.setText("");
    txtMarca.setText("");
    txtModelo.setText("");
    txtFabricacion.setText("");
    txtMante.setText("6 meses");
    txtEstado.setText("");
    txtEspecialidad.setSelectedItem("");
    txtCantidad.setValue(0);
    txtId.requestFocus();
    }
    
    void limpiarTable(DefaultTableModel model){
    for(int i =0 ; i <ListaDatos.getRowCount(); i++){
    model.removeRow(i);
    i = i - 1;
    }
    };
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ListaDatos;
    private javax.swing.JButton btnAgregar_RonaldinhoCcencho;
    private javax.swing.JButton btnEliminar_RonaldinhoCcencho;
    private javax.swing.JButton btnLimpiar_RonaldinhoCcencho;
    private javax.swing.JButton btnModificar_RonaldinhoCcencho;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner txtCantidad;
    private javax.swing.JComboBox<String> txtEspecialidad;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JFormattedTextField txtFabricacion;
    private javax.swing.JTextField txtId;
    private javax.swing.JRadioButton txtMante;
    private javax.swing.JTextField txtMarca;
    private javax.swing.JTextField txtModelo;
    // End of variables declaration//GEN-END:variables
}
